export const CartActionTypes = ({
  CURT_TOGGLE_HIDDEN: 'CURT_TOGGLE_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
})